project:
  type: website

website:
  title: "simple_quarto_website_two"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: about.ipynb
        text: About
      - href: slides/slides.ipynb
        text: Slides


format:
  html:
    theme: pulse
    toc: true



